# Site settings
title: Tuteja Lab
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://www.tuteja-lab.org"
url: "http://tuteja-lab.github.io.git"
# Build settings
markdown: kramdown
